# Generated by Django 4.2.7 on 2023-12-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docsits',
            unique_together={('doctor', 'hospital')},
        ),
    ]
