# Generated by Django 4.2.7 on 2023-11-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_hospital_medicalhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
