# Generated by Django 4.2.7 on 2023-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_docsits_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsits',
            name='chamber_no',
            field=models.CharField(max_length=20),
        ),
    ]
