# Generated by Django 4.2.7 on 2023-12-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_docsits_chamber_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hospitalroom',
            name='unique_room',
        ),
        migrations.AlterUniqueTogether(
            name='docsits',
            unique_together={('chamber_no', 'hospital')},
        ),
        migrations.AlterUniqueTogether(
            name='hospitalroom',
            unique_together={('branch', 'room_no')},
        ),
    ]
